### ISSUE TITLE
Add to nixpkgs

### ISSUE THREAD

**Issue by matthewbauer** [bennofs/nix-index#5]
It would be helpful if this package itself is in nixpkgs.

**Comment by bennofs** [comment]
Thanks for the reminder. I was planning to do that eventually, but I'd like to wait until the new version of `hyper`  (a dependency of `nix-index`) is released, since git dependencies are a little bit flaky in nixpkgs rust support.

**Comment by matthewbauer** [comment]
I guess eventually the hope is we can get all of crates in nixpkgs in the same way we do with haskellPackages?

**Comment by bennofs** [comment]
@matthewbauer that's not really necessary for rust crates, since generally applications depend on very specific versions of crates and there is no effort like `stackage` to create a consistent set. So basically you'd get very little sharing between applications. The approach right now is to just build all crates together with the application that requires them in the same derivation, so it's not necessary to have a set of crates like there is for haskell.

**Comment by matthewbauer** [comment]
Ok, I was just thinking it would be nice to have something like "cratePackages.*" for all packages instead of adding them each time to nixpkgs. Most seem to work without any significant modifications though, so that's good.

**Comment by bennofs** [comment]
Hyper `v0.11` was just released. I will look into adding it to nixpkgs soon.

**Comment by bennofs** [comment]
Fixed in https://github.com/NixOS/nixpkgs/commit/1d1735ce0f212ed634b5ab3b0d264f96aff2975d
